drivers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from . import views

app_name = 'drivers'

urlpatterns = [
  url(r'^$',views.driver, name = 'driver'),
  url(r'^profile/(?P<username>[-_\w.]+)/$', views.profile, name='profile'),
  url(r'^profile/(?P<username>[-_\w.]+)/edit/$', views.update_profile, name='edit'),
  url(r'^rider_profile/(\d+)/$', views.rider_profile, name='rider_profile'),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

ride/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', view.logout, {"next_page": '/'}),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^driver/', include('drivers.urls')),
    url(r'^rider/', include('rider.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

drivers/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.validators import RegexValidator
from rider.models import Rider_profile


# Create your models here.
class Driver_profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    bio = models.TextField(max_length=200, blank =True)
    city = models.CharField(max_length = 50, blank =True)
    phone_number =models.IntegerField(blank = True, null = True)
    profile_pic = models.ImageField(upload_to = 'profile_pic/', blank=True, null= True)
    car_model = models.CharField(max_length = 30, blank = True)
    car_number_plates = models.CharField(max_length = 30, blank = True)
    car_capacity = models.IntegerField(default = 0)
    car_image = models.ImageField(upload_to ='car_images/', blank =True, null =True)
    car_color = models.CharField(max_length = 30, blank =True)
    current_location = models.CharField(max_length = 10)
    destination = models.CharField(max_length = 30, blank = True, null = True)
    Free_space =models.PositiveIntegerField(default =0)




    @receiver(post_save, sender = User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Driver_profile.objects.create(user=instance)

    @receiver(post_save, sender = User)
    def save_user_profile(sender,instance, **kwargs):
        instance.driver_profile.save()
    @property
    def profile_pic_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url



class TripPlan(models.Model):
    driver_profile = models.ForeignKey(Driver_profile,on_delete=models.CASCADE )
    current_location = models.CharField(max_length = 30)
    destination = models.CharField(max_length = 30)


class Booking(models.Model):
    rider_profile = models.ForeignKey(Rider_profile,on_delete=models.CASCADE)
    trip_plan = models.ForeignKey(TripPlan,on_delete=models.CASCADE)

drivers/forms.py
from django import forms
from .models import Driver_profile,TripPlan
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name')

class DriverProfileForm(forms.ModelForm):
  class Meta:
    model = Driver_profile
    fields = ('bio', 'city','profile_pic', 'phone_number', 'car_image','car_capacity', 'car_number_plates', 'car_model','car_color', 'current_location','destination',)

class TripPlanForm(forms.ModelForm):
  class Meta:
    model = TripPlan
    fields = ('current_location','destination',)

drivers/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import UserForm, DriverProfileForm,TripPlanForm
from .models import Driver_profile,TripPlan
from rider.models import Rider_profile
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db import transaction

# Create your views here.
def driver(request):
  user = User.objects.get(username = request.user.username)
  profile = Driver_profile.objects.get(user =user)
  riders = Rider_profile.objects.all()
  if request.method == 'POST':
    trip_form = TripPlanForm(request.POST)
    if trip_form.is_valid():
      trip_plan= TripPlan(driver_profile = request.user.driver_profile, current_location = request.POST['current_location'],destination = request.POST['destination'])
      trip_plan.save()
      print('success')
      return redirect(reverse('drivers:driver'))
  else:
    trip_form = TripPlanForm()
  return render(request, 'drivers/driver.html',{"profile": profile, "riders": riders, "trip_form":trip_form})

@transaction.atomic
def update_profile(request,username):
  user = User.objects.get(username = username)
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance = request.user)
    profile_form = DriverProfileForm(request.POST, instance =request.user.driver_profile, files = request.FILES)
    if profile_form.is_valid() and user_form.is_valid():
      user_form.save()
      profile_form.save()
      messages.success(request, ('Your profile was successfully updated!'))
      return redirect(reverse('drivers:profile', kwargs = {'username': request.user.username}))
    else:
      messages.error(request, ('Please correct the error below.'))

  else:
    user_form = UserForm(instance = request.user)
    profile_form = DriverProfileForm(instance = request.user.driver_profile)
  return render(request, 'drivers/profiles/profile_form.html', {"user_form":user_form, "profile_form":profile_form})

@login_required(login_url='/accounts/login')
def profile(request, username):
  user = User.objects.get(username =username)
  if not user:
    return redirect('driver')
  profile = Driver_profile.objects.get(user =user)
  print(profile.profile_pic)

  title = f"{user.username}"

  return render(request, 'drivers/profiles/profile.html', {"title":title, "user":user, "profile": profile})


def rider_profile(request,rider_profile_id):
  user= User.objects.get(id = rider_profile_id)
  if user:
    rider_profile = Rider_profile.objects.get(user=user)
  return render(request,'drivers/rider_profile.html',{"rider_profile": rider_profile})

drivers/templates/drivers/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Ride</title>
  {% block styles%}
  {% bootstrap_css%}
  <link href="{% static 'css/driver.css' %}" rel="stylesheet">
  {% endblock %}
</head>
<body>

    {% include "drivers/navbar.html" %}



      {% block content %}
      {% endblock %}


    {% block scripts %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxICagWVIgKtKRXFDx6J3iKzkvI9X1Wv0&callback=initMap">
    </script>
    <script type="text/javascript" src="{% static 'js/driver.js' %}"></script>
    <script src="https://use.fontawesome.com/15a9a436fb.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/.3.7/js/bootstrap.min.js"></script>
    {% bootstrap_javascript %}
    {% endblock %}

</body>
</html>

drivers/templates/drivers/driver.html
{% extends 'drivers/base.html' %}
{% load static %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
  <div class="rider">
    <div class="row" id="row">
      <div class="col-md-2 side">
        {% if profile.profile_pic %}
        <img class="picture-circle" src="{{ profile.profile_pic.url }}">
        {% else %}
        <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %} <br>
        <h1 class="username">{{ user.first_name }}</h1>
        <hr>
        <a href="{% url 'drivers:profile' request.user.username%}">Profile</a>
      </div>
      <div class="col-md-8">
        <div class="row">
            <h2 class="text-center">Welcome {{ user.username }} </h2>
            <ul class="nav nav-tabs">
              <li class="active"><a data-toggle="tab" href="#home">Pick up points</a></li>
              <li><a data-toggle="tab" href="#drivers">Passengers</a></li>
              <li><a data-toggle="tab" href="#trip">Trip</a></li>
          </ul>

            <div class="tab-content">
              <div id="home" class="tab-pane fade in active">
                <h3>Map
                </h3>
                <div id="map"></div>
              </div>
              <div id="Pick_up" class="tab-pane fade">
                <h3>Comment</h3>
                <p>.</p>
              </div>
              <div id="drivers" class="tab-pane fade">
                <h3>Passengers</h3>
                {% for rider in riders%}
                <h1>
                  <a href="{% url 'drivers:rider_profile' rider.user.id%}">{{rider.user.username}}</a>
                </h1>
              {% endfor %}
              </div>
              <div id="trip" class="tab-pane fade">
                <div class="container">
                  <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                      {{ trip_form.current_location.label }} <br>
                      {{ trip_form.current_location }}
                      {{ trip_form.current_location.errors }}
                    </div>
                    <div class="form-group">
                      {{ trip_form.destination.label }} <br>
                      {{ trip_form.destination }}
                      {{ trip_form.destination.errors }}
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{% endblock %}

drivers/templates/drivers/navbar.html
{% load bootstrap3 %}
<div class="navbar navbar-default navbar-fixed-top" id="main-nav">
      <div class="container desktop">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">ride</a>
            <button type="button" data-toggle="collapse" data-target="#navbar-main" class="navbar-toggle">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar-main" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="/driver/"><i class="fa fa-home " aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="{% url 'drivers:profile' request.user.username %}"><i class="fa fa-user " aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="/logout"><i class="fa fa-sign-out " aria-hidden="true"></i></a>
                    </li>
                {% else %}
                    <li><a href="/accounts/login">Login</a></li>
                    <li><a href="/accounts/register/">Signup</a></li>
                {% endif %}
            </ul>
        </div>
      </div>
</div>
</html>

drivers/templates/drivers/rider_profile.html
{% extends 'drivers/base.html' %}
{% load static %}
{% load ratings %}

{% block content %}
<div class="container">

  <div class="profile">
    <div class="row">
      <div class="col-md-2 side">
        {% if rider_profile.profile_pic %}
        <img class="picture-circle" src="{{ rider_profile.profile_pic.url }}">
        {% else %}
        <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %} <br>
        <h1 class="username text-center">{{ rider_profile.user.username }}</h1>
        <h3>Review</h3>
        {% ratings rider_profile %}
      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-4">
            <h2>Details</h2>
          </div>
          <div class="col-md-4"></div>
          <div class="col-md-4 edit-prof">
            {% if  rider_profile.user == user %}
            <a class="edit-desktop" href="{% url 'drivers:edit' user.username %}">
              <button class="edit-profile">Edit Profile</button>
            </a>
            {% endif %}
          </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
              <div class="row">
                <h3>Name:</h3>
                  {{user.first_name}} {{user.last_name}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="row">
                <h3>City</h3>
                {{rider_profile.location}}
              </div>
            </div>
          </div>
          <hr>
            <div class="row">
              <div class="col-md-6">
                <div class="row">
                  <h3>Mobile</h3>
                    {{rider_profile.phone_number}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="row">
                  <h3>bio</h3>
                  {% if rider_profile.bio%}
                  {{rider_profile.bio}}
                  {% else %}
                  <p>This passenger doesnt have a bio yet</p>
                  {% endif %}
                </div>
              </div>
            </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>


{% endblock %}