ride/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', view.logout, {"next_page": '/'}),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^driver/', include('drivers.urls')),
    url(r'^rider/', include('rider.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

rider/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .import views

app_name = 'rider'

urlpatterns = [
  url(r'^$',views.rider, name = 'rider'),
  url(r'^profile/(?P<username>[-_\w.]+)/$', views.profile, name='profile'),
  url(r'^profile/(?P<username>[-_\w.]+)/edit/$', views.update_profile, name='edit'),
  url(r'^driver_profile/(\d+)/$', views.driver_profile, name='driver_profile'),
  url(r'^bookings/(\d+)/$', views.booking_seat, name ='bookings'),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

rider/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
# from drivers.models import Driver_profile


# Create your models here.
class Rider_profile(models.Model):
  user = models.OneToOneField(User, on_delete = models.CASCADE)
  bio = models.TextField(max_length=200, blank =True)
  location = models.CharField(max_length = 50, blank =True)
  phone_number =models.IntegerField(blank = True, null = True)
  profile_pic = models.ImageField(upload_to = 'profile_pic/', blank=True, null= True)


  @receiver(post_save, sender = User)
  def create_user_profile(sender, instance, created, **kwargs):
    if created:
      Rider_profile.objects.create(user=instance)

  @receiver(post_save, sender = User)
  def save_user_profile(sender,instance, **kwargs):
    instance.rider_profile.save()

rider/forms.py
from django import forms
from .models import Rider_profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name')

class ProfileForm(forms.ModelForm):
  class Meta:
    model = Rider_profile
    fields = ('bio', 'location','profile_pic', 'phone_number')

rider/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import UserForm,ProfileForm
from .models import Rider_profile
from drivers.models import Driver_profile,TripPlan,Booking
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def rider(request):
  user = User.objects.get(username = request.user.username)
  profile = Rider_profile.objects.get(user =user)
  drivers = Driver_profile.objects.all()
  return render(request, 'rider/rider.html', {"profile": profile, "drivers":drivers})


def update_profile(request,username):
  user = User.objects.get(username = username)
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance = request.user)
    profile_form = ProfileForm(request.POST, instance =request.user.rider_profile, files = request.FILES)
    if user_form.is_valid() and profile_form.is_valid():
      print('master')
      user_form.save()
      profile_form.save()
      messages.success(request, ('Your profile was successfully updated!'))
      return redirect(reverse('rider:profile', kwargs = {'username': request.user.username}))
    else:
      messages.error(request, ('Please correct the error below.'))

  else:
    user_form = UserForm(instance = request.user)
    profile_form = ProfileForm(instance = request.user.rider_profile)
  return render(request, 'rider/profiles/profile_form.html', {"user_form":user_form, "profile_form":profile_form})

@login_required
def profile(request, username):
  user = User.objects.get(username =username)
  if not user:
    return redirect('rider')
  profiles = Rider_profile.objects.get(user =user)

  title = f"{user.username}"

  return render(request, 'rider/profiles/profile.html', {"title":title, "user":user, "profiles": profiles})


#Rider sees a particular driver's profile
def driver_profile(request,driver_profile_id,trip_plan_id):
  user= User.objects.get(id = driver_profile_id)
  if user:
    driver_profile = Driver_profile.objects.get(user=user)
    trip_plan = TripPlan.objects.get(id = trip_plan_id)
    existing_bookings = Booking.objects.filter(trip_plan =trip_plan.id)
    if len(existing_bookings) < trip_plan.driver_profile.car_capacity:
      seats_left = trip_plan.driver_profile.car_capacity - len(existing_bookings)
      return render(request,'rider/driver_profile.html',{'driver_profile': driver_profile,"seats_left":seats_left,"trip_plan":trip_plan})
    elif len(existing_bookings) == trip_plan.driver_profile.car_capacity:
      message = "this ride is fully booked"
      return render(request,'rider/driver_profile.html',{'driver_profile': driver_profile,"message":message})

def booking_seat(request, driver_profile_id):
  current_user = request.user

  rider_profile = Rider_profile.objects.get(user= current_user)

  found_profile = Driver_profile.objects.get(id = driver_profile_id)

  trip_plan = TripPlan.objects.get(driver_profile = found_profile)

  existing_bookings = Booking.objects.filter(trip_plan=trip_plan)

  if len(existing_bookings) < trip_plan.driver_profile.car_capacity:
    new_booking = Booking(rider_profile= rider_profile, trip_plan = trip_plan)

    new_booking.save()

    print(new_booking)

  elif len(existing_bookings) == trip_plan.driver_profile.car_capacity:
    return redirect(reverse('rider:driver_profile', kwargs={'driver_profile_id':Driver_profile.user.id}))

rider/templates/rider/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Ride</title>
  {% block styles%}
  {% bootstrap_css%}
  <link href="{% static 'css/riders.css' %}" rel="stylesheet">
  {% endblock %}
</head>
<body>

    {% include "rider/navbar.html" %}
      {% block content %}
      {% endblock %}


      {% block scripts %}
      <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
      <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDXC5AIsZxhgdAbn-eHFNQlB8WsecAhjVs&callback=initMap">
      </script>
      <script src="https://use.fontawesome.com/15a9a436fb.js"></script>
      <script type="text/javascript" src="{% static 'js/driver.js' %}"></script>
      <script src="https://use.fontawesome.com/15a9a436fb.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/.3.7/js/bootstrap.min.js"></script>
      {% bootstrap_javascript %}
      {% endblock %}
</body>
</html>

rider/templates/rider/driver_profile.html
{% extends 'rider/base.html' %}

{% load static %}
{% load ratings %}

{% block content %}
<div class="container">

  <div class="profile">
    <div class="row">
      <div class="col-md-2 side">
        {% if driver_profile.profile_pic %}
        <img class="picture-circle" src="{{ driver_profile.profile_pic.url }}">
        {{profile.bio}}
        {% else %}
        <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %} <br>
        <h1 class="username text-center">{{ driver_profile.user.username }}</h1>
        <h3>Review</h3>
        {% ratings driver_profile %}
      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-4">
            <h2>Information</h2>
          </div>
          <div class="col-md-4"></div>
          <div class="col-md-4 edit-prof">
            {% if driver_profile.user == user %}
            <a class="edit-desktop" href="{% url 'rider:edit' user.username %}">
              <button class="edit-profile">Edit Profile</button>
            </a>
            {% endif %}
          </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
              <div class="row">
                <h3>Name:</h3>
                  {{user.first_name}} {{user.last_name}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="row">
                <h3>City</h3>
                {{driver_profile.city}}
              </div>
            </div>
          </div>
          <hr>
            <div class="row">
              <div class="col-md-6">
                <div class="row">
                  <h3>Mobile</h3>
                    {{driver_profile.phone_number}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="row">
                  <h3>Model</h3>
                  {{driver_profile.car_model}}
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                  <div class="row">
                    <h3>Car Number plate</h3>
                      {{driver_profile.car_number_plates}}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <h3>Car Image</h3>

                  </div>
                </div>
              </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                  <div class="row">
                    <h3>Car capacity:</h3>
                      {{driver_profile.car_capacity}}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <h3>Car Color:</h3>
                    {{driver_profile.car_color}}
                  </div>
                </div>
              </div>


      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>


{% endblock %}

rider/templates/rider/navbar.html
{% load bootstrap3 %}
<div class="navbar navbar-default navbar-fixed-top" id="main-nav">
      <div class="container desktop">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">ride</a>
            <button type="button" data-toggle="collapse" data-target="#navbar-main" class="navbar-toggle">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar-main" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="/rider/"><i class="fa fa-home " aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="{% url 'rider:profile' request.user.username %}"><i class="fa fa-user " aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="/logout"><i class="fa fa-sign-out " aria-hidden="true"></i></a>
                    </li>
                {% else %}
                    <li><a href="/accounts/login">Login</a></li>
                    <li><a href="/accounts/register/">Signup</a></li>
                {% endif %}
            </ul>
        </div>
      </div>
</div>

rider/templates/rider/rider.html
{% extends 'rider/base.html' %}
{% load static %}
{% block content %}
<div class="container">

  <div class="rider">
    <div class="row" id="row">
      <div class="col-md-2 side">
        {% if profile.profile_pic %}
        <img class="picture-circle" src="{{ profile.profile_pic.url }}">
        {{profile.bio}}
        {% else %}
        <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %} <br>
        <h1 class="username">{{ user.first_name }}</h1>
        <hr>
        <a href="{% url 'rider:profile' request.user.username%}">Profile</a>
      </div>
      <div class="col-md-8">
        <div class="row">
            <h2 class="text-center">Welcome {{ user.username }} </h2>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home">Pick up points</a></li>
                <li><a data-toggle="tab" href="#drivers">Drivers</a></li>
                <li><a data-toggle="tab" href="#review">Review</a></li>
              </ul>

              <div class="tab-content">
                <div id="home" class="tab-pane fade in active">
                  <h3>HOME</h3>
                  <div id="map"></div>
                </div>
                <div id="drivers" class="tab-pane fade">
                  <h3>Drivers</h3>
                  {% for driver in drivers%}
                    <h1>
                      <a href="{% url 'rider:driver_profile' driver.user.id%}">{{driver.user.username}}</a>
                    </h1>
                  {% endfor %}
                </div>
                <div id="review" class="tab-pane fade">
                  <h3>comments</h3>
                  <p>awesome driver.</p>
                </div>
              </div>
            </div>
          </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>

</div>
{% endblock %}